// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Spl2.Models;

namespace Spl2.Migrations
{
    [DbContext(typeof(Spl2Context))]
    [Migration("20190421182136_InitialMigrate6")]
    partial class InitialMigrate6
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Spl2.Models.DailyStudentServiceList", b =>
                {
                    b.Property<string>("Session")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("DrugList")
                        .IsRequired()
                        .HasColumnType("varchar(7000)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("problemDetails")
                        .IsRequired()
                        .HasColumnType("varchar(600)");

                    b.Property<string>("studentname")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("Session");

                    b.ToTable("dailyStudentServiceLists");
                });

            modelBuilder.Entity("Spl2.Models.DrugInfoPerStudent", b =>
                {
                    b.Property<string>("name")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Session")
                        .IsRequired();

                    b.Property<int>("amount");

                    b.HasKey("name");

                    b.HasIndex("Session");

                    b.ToTable("drugInfoPerStudents");
                });

            modelBuilder.Entity("Spl2.Models.DrugInfoPerStudent", b =>
                {
                    b.HasOne("Spl2.Models.DailyStudentServiceList")
                        .WithMany("DrugInfoPerStudents")
                        .HasForeignKey("Session")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
