//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TableSplitting
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeData
    {
        public int EmployeeID { get; set; }
        public string Name { get; set; }
        public int Salary { get; set; }
    
        public virtual EmployeeDetails EmployeeDetails { get; set; }
    }
}
