//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TableSplitting
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeDetails
    {
        public int EmployeeID { get; set; }
        public string PhnNumber { get; set; }
        public string Email { get; set; }
    
        public virtual EmployeeData EmployeeData { get; set; }
    }
}
